name       : qt5-serialbus
version    : 5.12.3
release    : 13
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtserialbus-everywhere-src-5.12.3.tar.xz : 792cd2d411d2ebd737f5d09580f8db479cd35f2f7e7cedb4412075ef20fcfe4d
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Serial Bus Module
description: |
    The Qt Serial Bus API provides classes and functions to access the various industrial serial buses and protocols, such as CAN, ModBus, and others. This module is currently released as a Technology Preview.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5SerialPort)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialbus.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
