name       : qt5-serialbus
version    : 5.12.1
release    : 11
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtserialbus-everywhere-src-5.12.1.tar.xz : 97f0c690c77b0e19a8c90e376ecc94d59b21adb20a90179700d1c514a4c50d74
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Serial Bus Module
description: |
    The Qt Serial Bus API provides classes and functions to access the various industrial serial buses and protocols, such as CAN, ModBus, and others. This module is currently released as a Technology Preview.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5SerialPort)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialbus.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
