name       : qt5-serialbus
version    : 5.15.10
release    : 29
source     :
    - git|https://invent.kde.org/qt/qt/qtserialbus.git : b3081c36baee48b43b6285b4811dc6da451e2390
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Serial Bus Module
description: |
    The Qt Serial Bus API provides classes and functions to access the various industrial serial buses and protocols, such as CAN, ModBus, and others. This module is currently released as a Technology Preview.
builddeps  :
    - pkgconfig(Qt5SerialPort)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialbus.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
