name       : qt5-serialbus
version    : 5.9.2
release    : 5
source     :
    - https://download.qt.io/official_releases/qt/5.9/5.9.2/submodules/qtserialbus-opensource-src-5.9.2.tar.xz : bbc24bdafd0191fc808e08b19f378e74bedbb79faf4e396b66ba7ca9fed9be08
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Serial Bus Module
description: |
    The Qt Serial Bus API provides classes and functions to access the various industrial serial buses and protocols, such as CAN, ModBus, and others. This module is currently released as a Technology Preview.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5SerialPort)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialbus.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
