name       : qt5-serialbus
version    : 5.15.1
release    : 19
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtserialbus-everywhere-src-5.15.1.tar.xz : 9ee220826032ae1f8e68d9ec7dddc10ddc4c2e0a771d34009ae307b07eeca751
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Serial Bus Module
description: |
    The Qt Serial Bus API provides classes and functions to access the various industrial serial buses and protocols, such as CAN, ModBus, and others. This module is currently released as a Technology Preview.
builddeps  :
    - pkgconfig(Qt5SerialPort)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtserialbus.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
